name: VPS

on:
  workflow_dispatch:

jobs:
  vps:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:

      - name: Restore Backup
        uses: actions/download-artifact@v4
        with:
          name: vps-backup
          path: restore
        continue-on-error: true

      - name: Extract Backup
        run: |
          if [ -f restore/backup.tar.gz ]; then
            echo "Restoring VPS data..."
            tar -xzf restore/backup.tar.gz -C /
          else
            echo "No backup found"
          fi

      - name: Start VPS SSH
        run: |
          curl -sSf https://sshx.io/get | sh -s run &

      - name: Auto Backup Loop
        run: |
          while true
          do
            sleep 3600
            echo "Creating backup..."

            sudo tar \
            --exclude=/proc \
            --exclude=/sys \
            --exclude=/dev \
            --exclude=/run \
            --exclude=/tmp \
            -czf backup.tar.gz /home

          done

      - name: Upload Backup
        uses: actions/upload-artifact@v4
        with:
          name: vps-backup
          path: backup.tar.gz
          retention-days: 7
